/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_livecoding_demo_LlamaJNI */

#ifndef _Included_com_livecoding_demo_LlamaJNI
#define _Included_com_livecoding_demo_LlamaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_livecoding_demo_LlamaJNI
 * Method:    loadModel
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_livecoding_demo_LlamaJNI_loadModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_livecoding_demo_LlamaJNI
 * Method:    generateText
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_livecoding_demo_LlamaJNI_generateText
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_livecoding_demo_LlamaJNI
 * Method:    unloadModel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_livecoding_demo_LlamaJNI_unloadModel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_livecoding_demo_LlamaJNI
 * Method:    getModelInfo
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_livecoding_demo_LlamaJNI_getModelInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_livecoding_demo_LlamaJNI
 * Method:    isModelLoaded
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_livecoding_demo_LlamaJNI_isModelLoaded
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
